name: Deploy Patient App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies and build the React app
    - name: Install Dependencies and Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build

    # Step 4: Set up SSH access to EC2 instance
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    # Step 5: Deploy to EC2 instance
    - name: Deploy React App to EC2
      run: |
        scp -r frontend/build ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/patient-app/frontend
        ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd ~/patient-app
          # Optional: Restart backend if required
          pm2 restart all || pm2 start npm --name "patient-backend" -- start
        EOF
